#' @section \code{use_cmake}:
#' Adds a \code{CMakeLists.txt} file to the project and generates a build directory
#' (at \code{<pkg>-build}), which IDEs can use to open and provide code navigation
#' and completion.
#' @export
#' @name infrastructure
#' @rdname infrastructure
use_cmake <- function(pkg = ".") {
  pkg <- as.package(pkg)

  platforms <- list(
    Windows = use_cmake_windows(pkg = pkg),
    Mac = use_cmake_mac(pkg = pkg),
    Linux = use_cmake_linux(pkg = pkg)
  )

  output <- c(
    "## CMakeLists.txt automatically generated by devtools::use_cmake()",
    "",
    cmake_if("UNIX", platforms$Linux),
    "",
    cmake_if("WIN32", platforms$Windows),
    "",
    cmake_if("APPLE", platforms$Mac)
  )

  cat(output, file = file.path(pkg$path, "CMakeLists.txt"), sep = "\n")

  use_build_ignore("CMakeLists.txt", pkg = pkg)
  message("'CMakeLists.txt' file successfully generated.")

}

#' @section \code{use_xcode}:
#' Allows an \R package containing C/C++ source files to be managed from within
#' the XCode IDE.
#' @export
#' @name infrastructure
#' @rdname infrastructure
use_xcode <- function(pkg = ".") {
  pkg <- as.package(pkg)
  use_cmake(pkg = pkg)
  cmake <- Sys.which("cmake")
  if (cmake == "") {
    stop("No 'cmake' executable could be found; cannot build XCode project scaffolding")
  }

  rel_build_path <- paste(pkg$package, "xcode", "build", sep = "-")
  build_path <- file.path(
    pkg$path,
    rel_build_path
  )

  if (dir.exists(build_path)) {
    stop("Path '", build_path, "' already exists!")
  }

  dir.create(build_path, showWarnings = FALSE)
  with_dir(build_path, {
    system2("cmake", c("-GXcode", "..", "-Wno-dev"))
  })

  use_build_ignore(rel_build_path, pkg = pkg)

  open <- paste("open", file.path(build_path, paste0(pkg$package, ".xcodeproj")))

  msg <- c(
    "XCode project files successfully generated. Open the project in XCode with:\n\n    ",
    open,
    "\n\nor by manually opening the project from within XCode."
  )
  message(msg)
  open

}

with_dir <- function(dir, expr) {
  owd <- getwd()
  on.exit(setwd(owd))
  setwd(dir)
  force(expr)
}

cmake_if <- function(platform, code) {
  c(
    paste0("if (", platform, ")"),
    paste0("  ", gsub("\n", "\n  ", code)),
    "endif()"
  )
}

make_directives <- function(list, collapse = FALSE) {
  output <- character(length(list))
  for (i in seq_along(list)) {
    output[[i]] <- paste0(
      names(list)[[i]],
      if (collapse) "(" else "(\n  ",
      paste(list[[i]], collapse = if (collapse) " " else "\n  "),
      if (collapse) ")\n" else "\n)\n"
    )
  }
  output
}

make_file_directive <- function(manipulation, variable, exprs) {
  paste0(
    "file(",
    manipulation, " ",
    variable, "\n  ",
    paste(exprs, collapse = "\n  "),
    "\n)"
  )
}

make_library_directive <- function(name, link, vec) {
  paste0(
    "add_library(",
    name, " ",
    link, "\n  ",
    paste(vec, collapse = "\n  "),
    "\n)\n"
  )
}

make_set_directives <- function(list) {
  output <- character(length(list))
  for (i in seq_along(list)) {
    output[[i]] <- paste0(
      "set(",
      names(list)[[i]],
      "\n  ",
      paste(list[[i]], collapse = "\n  "),
      "\n)\n"
    )
  }
  output
}

base_cmake_directives <- function(pkg) {
  list(
    cmake_minimum_required = "VERSION 2.8 FATAL_ERROR",
    project = pkg$package
  )
}

package.file <- function(..., package, mustWork = TRUE) {
  result <- setNames(vapply(package, FUN.VALUE = character(1), function(pkg) {
    system.file(..., package = pkg, mustWork = mustWork)
  }), package)
  result[result != ""]
}

use_cmake_linux <- function(pkg) {
  ## TODO
}

use_cmake_windows <- function(pkg) {
  ## TODO
}

use_cmake_mac <- function(pkg) {

  lead_directives <- base_cmake_directives(pkg = pkg)

  ## Add include directories
  base_directives <- list()
  base_directives$include_directories <- c(
    R.home("include"),
    unname(package.file("include", package = pkg_linking_to(pkg))),
    "inst/include",
    "/usr/local/include",
    "/usr/include"
  )

  ## Add link directories
  base_directives$link_directories <- c(
    R.home("lib"),
    unname(package.file("lib", package = pkg_linking_to(pkg), mustWork = FALSE))
  )

  base_directives$link_libraries <- c(
    "libR.dylib"
  )

  base_directives$add_compile_options <- c(
    "-fPIC",
    "-g",
    "-O3",
    "-Wall"
  )

  base_directives$add_definitions <- "-DNDEBUG"

  set_directives <- list()
  set_directives$CMAKE_EXE_LINKER_FLAGS <- c(
    "-dynamiclib",
    "-Wl,-headerpad_max_install_names",
    "-undefined dynamic_lookup",
    "-single_module",
    "-multiply_defined suppress",
    "-Wl,CoreFoundation"
  )

  pkgname_upper <- toupper(pkg$package)

  source_file_globs <- c(
    "src/*.cpp",
    "src/*.c"
  )

  header_file_globs <- c(
    "src/*.hpp",
    "src/*.h",
    "inst/include/*.h"
  )

  file_directives <- c(

    make_file_directive("GLOB_RECURSE",
                        paste0(pkgname_upper, "_SOURCES"),
                        source_file_globs),

    make_file_directive("GLOB_RECURSE",
                        paste0(pkgname_upper, "_HEADERS"),
                        header_file_globs),

    make_file_directive("GLOB_RECURSE",
                        paste0(pkgname_upper, "_R"),
                        "R/*"),

    make_file_directive("GLOB_RECURSE",
                        paste0(pkgname_upper, "_MAN"),
                        "man/*"),

    make_file_directive("GLOB_RECURSE",
                        paste0(pkgname_upper, "_TESTS"),
                        "tests/*"),

    make_file_directive("GLOB_RECURSE",
                        paste0(pkgname_upper, "_VIGNETTES"),
                        "vignettes/*"),

    make_file_directive("GLOB_RECURSE",
                        paste0(pkgname_upper, "_INST"),
                        "inst/*")
  )

  add_library_directive <- c(
    paste0("${", pkgname_upper, "_SOURCES}"),
    paste0("${", pkgname_upper, "_HEADERS}"),
    paste0("${", pkgname_upper, "_R}"),
    paste0("${", pkgname_upper, "_MAN}"),
    paste0("${", pkgname_upper, "_TESTS}"),
    paste0("${", pkgname_upper, "_VIGNETTES}"),
    paste0("${", pkgname_upper, "_INST}")
  )

  all <- c(
    make_directives(lead_directives, collapse = TRUE),
    "## File directives -- this may need to be updated manually if",
    "## project files are not in one of the standard R directories",
    file_directives,
    "## Main directives -- this may need to be updated manually if",
    "## you are making use of libraries not declared in the DESCRIPTION.",
    make_directives(base_directives, collapse = FALSE),
    "",
    make_set_directives(set_directives),
    make_set_directives(list(CMAKE_SKIP_BUILD_RPATH = "TRUE")),
    make_library_directive(pkg$package, "SHARED", add_library_directive)
  )

}
