#' @section \code{use_cmake}:
#' Adds a \code{CMakeLists.txt} file to the project, which IDEs can use to
#' properly build the project.
#' @export
#' @name infrastructure
#' @rdname infrastructure
use_cmake <- function(pkg = ".") {
  pkg <- as.package(pkg)

  switch (Sys.info()[["sysname"]],
          "Windows" = use_cmake_windows(pkg = pkg),
          "Darwin" = use_cmake_mac(pkg = pkg),
          "Linux" = use_cmake_linux(pkg = pkg),
          stop("Unrecognized system type '", Sys.info()[["sysname"]], "'")
  )
}

make_directives <- function(list, collapse = FALSE) {
  output <- character(length(list))
  for (i in seq_along(list)) {
    output[[i]] <- paste0(
      names(list)[[i]],
      if (collapse) "(" else "(\n  ",
      paste(list[[i]], collapse = if (collapse) " " else "\n  "),
      if (collapse) ")\n" else "\n)\n"
    )
  }
  output
}

make_file_directive <- function(manipulation, variable, exprs) {
  paste0(
    "file(",
    manipulation, " ",
    variable, "\n  ",
    paste(exprs, collapse = "\n  "),
    "\n)"
  )
}

make_library_directive <- function(name, link, vec) {
  paste0(
    "add_library(",
    name, " ",
    link, "\n  ",
    paste(vec, collapse = "\n  "),
    "\n)\n"
  )
}

make_set_directives <- function(list) {
  output <- character(length(list))
  for (i in seq_along(list)) {
    output[[i]] <- paste0(
      "set(\n  ",
      names(list)[[i]],
      "\n  ",
      paste(list[[i]], collapse = "\n  "),
      "\n)\n"
    )
  }
  output
}

base_cmake_directives <- function(pkg) {
  list(
    cmake_minimum_required = "VERSION 2.8 FATAL_ERROR",
    project = pkg$package
  )
}

package.file <- function(..., package, mustWork = TRUE) {
  result <- setNames(vapply(package, FUN.VALUE = character(1), function(pkg) {
    system.file(..., package = pkg, mustWork = mustWork)
  }), package)
  result[result != ""]
}

use_cmake_mac <- function(pkg) {

  lead_directives <- base_cmake_directives(pkg = pkg)

  ## Add include directories
  base_directives <- list()
  base_directives$include_directories <- c(
    R.home("include"),
    unname(package.file("include", package = pkg_linking_to(pkg))),
    "inst/include",
    "/usr/local/include",
    "/usr/include"
  )

  ## Add link directories
  base_directives$link_directories <- c(
    R.home("lib"),
    unname(package.file("lib", package = pkg_linking_to(pkg), mustWork = FALSE))
  )

  base_directives$link_libraries <- c(
    "libR.dylib"
  )

  base_directives$add_compile_options <- c(
    "-fPIC",
    "-g",
    "-O3",
    "-Wall"
  )

  base_directives$add_definitions <- "-DNDEBUG"

  set_directives <- list()
  set_directives$CMAKE_EXE_LINKER_FLAGS <- c(
    "-dynamiclib",
    "-Wl,-headerpad_max_install_names",
    "-undefined dynamic_lookup",
    "-single_module",
    "-multiply_defined suppress",
    "-Wl,CoreFoundation"
  )

  pkgname_upper <- toupper(pkg$package)

  source_file_directive <- c(
    "src/*.cpp",
    "src/*.c"
  )

  header_file_directive <- c(
    "src/*.hpp",
    "src/*.h",
    "inst/include/*.h"
  )

  add_library_directive <- c(
    paste0("${", pkgname_upper, "_SOURCES}"),
    paste0("${", pkgname_upper, "_HEADERS}")
  )

  all <- c(
    "## CMakeLists.txt automatically generated by devtools::use_cmake()",
    "",
    make_directives(lead_directives, collapse = TRUE),
    make_file_directive("GLOB_RECURSE",
                        paste0(pkgname_upper, "_SOURCES"),
                        source_file_directive),
    "",
    make_file_directive("GLOB_RECURSE",
                        paste0(pkgname_upper, "_HEADERS"),
                        header_file_directive),
    "",
    make_directives(base_directives, collapse = FALSE),
    "",
    make_set_directives(set_directives),
    make_library_directive(pkg$package, "SHARED", add_library_directive)

  )

  cat(all, file = file.path(pkg$path, "CMakeLists.txt"), sep = "\n")

  build_path <- file.path(pkg$path, paste(pkg$package, "build", sep = "-"))

  cmake <- Sys.which("cmake")
  if (cmake != "") {
    dir.create(build_path)

    owd <- getwd()
    setwd(build_path)
    on.exit(setwd(owd))

    system2("cmake", c("..", "-Wno-dev"))
  }

}
